
[workspace]
members = [
    "smoldb",
    "smoldb_derive",
    "smoldb_traits",
]

[patch.crates-io]
smoldb = { path = "./smoldb" }
smoldb_derive = { path = "./smoldb_derive" }
smoldb_traits = { path = "./smoldb_traits" }
